Сделали задание «Анимируем смены состояний интерактивных элементов» М…
htmlacademy-animation/1533569-magic-vacation-1 pull request #1
Opened 2020-07-16 19:08 UTC by ruslovzi

…одуль 1

2020-07-17 07:39 UTC, abeluzhenko requested changes

2020-07-17 07:39 UTC, abeluzhenko commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
Нет необходимости изменять отступы и ширину элемента для создания анимации. Здесь проще всего использовать свойство `transform: translateX(200%)`, (200% - чтобы поле наверняка ушло за границы экрана) таким же образом, как и при создании fadeIn эффекта в разделе "история"

2020-07-17 07:39 UTC, abeluzhenko commented on source/scss/blocks/form.scss
> +  width: calc(100% - 21rem);
В момент, когда элемент становится активным можно просто сбросить свойство `transition`, установив значение `none` или `translateX(0)`

2020-07-17 15:49 UTC, ruslovzi commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
Пробовал использовать `transform: translateX(200%)`, но тогда анимация отличается от той, что на видео, так как форма выезжает из-за пределе кнопки справа, поэтому решил попробовать такое решение (не очень красивое, но вроде сработало). Или я что-то не правильно понял в вашем объяснении?

2020-07-17 15:52 UTC, ruslovzi commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
> Нет необходимости изменять отступы и ширину элемента для создания анимации. Здесь проще всего использовать свойство `transform: translateX(200%)`, (200% - чтобы поле наверняка ушло за границы экрана) таким же образом, как и при создании fadeIn эффекта в разделе "история"

Есть мысль дать родитель `justify-content: flex-end;` и убрать у кнопки `flex-grow`. Но так как 1 модуль посвящен `transition` подумал, что это слишком..

2020-07-18 05:49 UTC, abeluzhenko commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
@ruslovzi действительно, на видео более сложный вариант с анимацией свойства `clip-path`. У `.form-field` вы можете установить для этого свойства значение `inset(0 0 0 100%)`, когда страница скрыта и `inset(0 0 0 0)`, когда страница активна. И это даст такой же эффект, без изменения ширины элемента.

Но на самом деле на данном этапе это не так важно, чтобы эффекты были один-в-один как в видео, главное, чтобы вы поняли принцип.

Я "вцепился" в этот кусок из опасений что такие изменения в верстке могут привести к трудностям при выполнении следующих заданий (от них уже страдает адаптивность, анимация выглядит некорректно при средней ширине экрана).

2020-07-18 05:58 UTC, abeluzhenko commented on source/scss/blocks/screen.scss
> +    // display: none; // убрали данный класс, так как в первом модуле мешает реализовывать задачи
Есть более простое решение: всесто `display: none;` использовать `visibility: hidden;`
Эффект будет тот же - у вложенных элементов не будет сбрасываться стейт анимаций, но экран будет невидим для пользователя и событий мыши.

2020-07-19 08:14 UTC, ruslovzi commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
> @ruslovzi действительно, на видео более сложный вариант с анимацией свойства `clip-path`. У `.form-field` вы можете установить для этого свойства значение `inset(0 0 0 100%)`, когда страница скрыта и `inset(0 0 0 0)`, когда страница активна. И это даст такой же эффект, без изменения ширины элемента.
> 
> Но на самом деле на данном этапе это не так важно, чтобы эффекты были один-в-один как в видео, главное, чтобы вы поняли принцип.
> 
> Я "вцепился" в этот кусок из опасений что такие изменения в верстке могут привести к трудностям при выполнении следующих заданий (от них уже страдает адаптивность, анимация выглядит некорректно при средней ширине экрана).

Принял! Спасибо за объяснение, про свойство `clip-path` не знал. Почитаю, полезно :)

Подскажите пожалуйста, как считать задание выполненным? Вы должны его одобрить? Потому что в остальном, с анимацией вроде все ок?

2020-07-19 08:16 UTC, ruslovzi commented on source/scss/blocks/screen.scss
> +    // display: none; // убрали данный класс, так как в первом модуле мешает реализовывать задачи
> Есть более простое решение: всесто `display: none;` использовать `visibility: hidden;`
> Эффект будет тот же - у вложенных элементов не будет сбрасываться стейт анимаций, но экран будет невидим для пользователя и событий мыши.

насколько мне известно `visibility: hidden;` не уберет размеров DOM элемента? Конечно, можно дополнительно задать тот же `transform: scale(0);. Но посыл понял, можно проще реализовать данную задачу.

2020-07-19 10:35 UTC, abeluzhenko commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
Отправьте еще раз на проверку и я или другой наставник примет работу.

2020-07-19 11:51 UTC, ruslovzi commented on source/scss/blocks/form.scss
> +  margin-left: calc(100% - 21rem);
> Отправьте еще раз на проверку и я или другой наставник примет работу.

Внес обновление в код по вашим рекомендациям, отправил на проверку

2020-07-19 13:37 UTC, merged